const translations = {
    "EN": {
        "home": "HOME",
        "nft": "NFT",
        "tokenomics": "TOKENOMICS",
        "langSwitch": "LANG EN/KR",
        "apartmentDescription": "Apartment - Maybe one day you’ll have a house.",
        "apartmentDescription2": "Apartment is the embodiment of the hopium us degenerates posses.",
        "buyNow": "BUY NOW",
        "followUs": "FOLLOW US",
        "nftDescription": "Apartment NFTs Stand As Dynamic Digital Reflections Of Our Contemporary Existence, Encapsulating The Essence Of Our Digital Age. Each Virtual Apartment Embodies The Quintessence Of Our Lifestyle, Offering A Whitelist Spot For The Least Anticipated Token Launch On Aptos... Apartment.",
        "apartmentsStaking": "APARTMENTS ARE ALSO ABLE TO BE STAKED FOR A LINEAR RETURN IN $APT",
        "totalSupply": "TOTAL SUPPLY: 00000000000000000000000",
        "ourCommunity": "Our Community Is Made Up Of Likeminded Degen’s With One Goal In Mind… To Buy A House.",
        "privacyPolicy": "Privacy Policy",
        "cookies": "Cookies",
        "termsConditions": "Terms & Conditions",
        "aptosApartments": "Aptos Apartments 2024- ALL Rights Reserved",
    },
    "KO": {
        "home": "홈",
        "nft": "NFT",
        "tokenomics": "토큰 이코노미",
        "langSwitch": "언어 EN/KR",
        "apartmentDescription": "아파트 - 언젠가 당신은 집을 가질 것입니다.",
        "apartmentDescription2": "아파트는 우리가 가지고 있는 희망의 구현입니다.",
        "buyNow": "지금 구매하기",
        "followUs": "우리를 따라오세요",
        "nftDescription": "아파트 NFT는 우리의 현대 존재의 동적 디지털 반영으로, 디지털 시대의 본질을 담고 있습니다. 각 가상 아파트는 우리의 라이프 스타일의 정수를 구현하며, Aptos에서 가장 기대되지 않는 토큰 출시를 위한 화이트리스트 자리를 제공합니다.",
        "apartmentsStaking": "아파트도 $APT에서 선형 수익을 위해 스테이킹할 수 있습니다",
        "totalSupply": "총 공급량: 00000000000000000000000",
        "ourCommunity": "우리 커뮤니티는 하나의 목표를 가진 마음이 맞는 디제너레이트로 구성되어 있습니다... 집을 사다.",
        "privacyPolicy": "개인정보 처리방침",
        "cookies": "쿠키",
        "termsConditions": "이용 약관",
        "aptosApartments": "Aptos 아파트 2024- 모든 권리 보유",
    }
};
